package com.hexagonal.spring_practice_hexagonal.infrastructure.config;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;


@Configuration
public class SwaggerConfig {

        // This method configures the OpenAPI documentation
        @Bean
        OpenAPI customOpenAPI() {
                return new OpenAPI()
                                .components(new Components())
                                .info(new Info()
                                                .title("Assignation Tasks API")
                                                .description(
                                                                "This API represents Task Assignation to do")
                                                .version("v0.0.1")
                                                .license(new License().name("Apache 2.0").url("http://springdoc.org")));
        }

        // Use only paths generated by the API
        @Bean
        GroupedOpenApi api() {
                return GroupedOpenApi.builder().group("sitas")
                                .packagesToScan("com.hexagonal.spring_practice_hexagonal.infrastructure.controllers")
                                .pathsToMatch("/api/v1/tasks/**").build();
        }

        //exclude put endpoints from path placement-area
}